### ISSUE TITLE
Instructions for use?

### ISSUE THREAD

**Issue by CoderBrandon** [cylleneius/fft_map_to_obj#1]
I was playing around with this and got this to export an obj, but it didn't have any textures. It looks like I might be misunderstanding what is needed for the second parameter. For reference, I tried all the MAP022.X files in the second parameter without any luck. Can you provide some basic instructions for use? Thanks!

**Comment by cylleneius** [comment]
Ah, apologies. My younger self never bothered with instructions/documentation. The map data are paired I believe, and not all of the pairings will produce meshes. The `.gns` files are for the second parameter and I think the textures it outputs are raw pixel values, so you may need to convert them to a usable container format. I had a converter to PNG working at one point, I'll see if I can find it.

**Comment by cylleneius** [comment]
Nope. I was wrong. The `.gns` files are useless with this tool. They are paired though (I think). It's been awhile.

`map002.9 map002.16` produces a texture file `map002.16_palette0.tex` loadable by the gimp's raw image data, 256x1024. If you flip the image vertically and save it as png you can use this .mtl (save as `map002.9.mtl`)to load the mesh with texture:
>newmtl  blah
Ns 100.000
d 1.00000
illum 2
Kd 1.00000 1.00000 1.00000
Ka 1.00000 1.00000 1.00000
Ks 1.00000 1.00000 1.00000
Ke 1.00000 1.00000 1.00000
map_Kd map002.16_palette0.png

**Comment by cylleneius** [comment]
I found time to work on this. e14c2531cf405403bf2245b734e87802cd68e5d1 should help.
